###################################################################
#
# generate_report
#
# Generates a sanitization report based on detected PII findings.
# The function summarizes the number of each type of sensitive
# information found, determines an overall risk level, and returns
# the sanitized version of the input text.
# Authors:
# Yas'lyn Mohammed
# Reem Khalid
# Kai'lyn Mohammed
# 
# Risk level:
# high - if SSNs or credit card numbers are detected
# medium - if other PII (emails or phone numbers) are detected
# low - if no PII is detected
#
# Parameters:
# sanitized_text : str (The text after PII has been anonymized or removed.)
# findings : list of dict (A list of detected PII findings generated by detect_pii()) 
#
# Each item has the structure:
#
#       {
#         "type": "email" | "phone" | "ssn" | "credit_card",
#         "start": int,
#         "end": int
#       }
#
# Returns:
# report : dict (A dictionary summarizing the sanitization results)
#
# Example return structure:
#
# {
#     "risk_level": "medium",
#     "total_findings": 2,
#     "findings_by_type": {
#         "email": 1,
#         "phone": 1,
#         "ssn": 0,
#         "credit_card": 0
#     },
#     "sanitized_text": "My email is [EMAIL_INFORMATION_REDACTED]"
# }
#
###################################################################


def generate_report(sanitized_text, findings):
    counts = {
        "email": 0,
        "phone": 0,
        "ssn": 0,
        "credit_card": 0
    }

    for item in findings: 
        pii_type = item["type"]
        if pii_type in counts:
            counts[pii_type] += 1

    if counts["ssn"] > 0 or counts["credit_card"] > 0:
        risk = "high"
    elif len(findings) > 0:
        risk = "medium"
    else:
        risk = "low"

    report = {
        "risk_level": risk,
        "total_findings": len(findings),
        "findings_by_type": counts,
        "sanitized_text": sanitized_text
    }

    return report