###################################################################
#
# sanitize_text
#
# Replaces detected PII in the input text with redacted placeholders.
# The function iterates through detected findings and substitutes
# each occurrence of sensitive data with a standardized redaction
# label indicating the type of information removed.
#
# Authors:
# Yas'lyn Mohammed
# Reem Khalid
# Kai'lyn Mohammed
#
# Parameters:
# text : str (The original input text that may contain PII)
# findings : list of dict (A list of detected PII findings generated by detect_pii())
#
# Each item has the structure:
#
#       {
#         "type": "email" | "phone" | "ssn" | "credit_card",
#         "start": int,
#         "end": int
#       }
#
# Behavior:
# Each detected PII instance is replaced with a placeholder
# formatted as:
#
#   [TYPE_INFORMATION_REDACTED]
#
# Example replacements:
#   email -> [EMAIL_INFORMATION_REDACTED]
#   phone -> [PHONE_INFORMATION_REDACTED]
#   ssn -> [SSN_INFORMATION_REDACTED]
#   credit_card -> [CREDIT_CARD_INFORMATION_REDACTED]
#
# Returns:
# sanitized_text : str (The input text with all detected PII replaced
#                       by redacted placeholders)
#
# Example output:
#
# Input:
# "My email is user@example.com and my phone is 555-123-4567"
#
# Output:
# "My email is [EMAIL_INFORMATION_REDACTED] and my phone is
#  [PHONE_INFORMATION_REDACTED]"
#
###################################################################
def sanitize_text(text, findings):
    result = text
    for item in sorted(findings, key=lambda x: x["start"], reverse=True):
        pii_type = item["type"]
        start = item["start"]
        end = item["end"]
        result = result[:start] + f"[{pii_type.upper()}_INFORMATION_REDACTED]" + result[end:]

    return result